# Generated by Django 5.1.1 on 2024-09-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Максимум 100', max_length=100, verbose_name='Название смартфона')),
                ('description', models.TextField(verbose_name='Напишите описание')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография смартфона')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('phone_make', models.CharField(choices=[('IPhone', 'IPhone'), ('Samsung Galaxy', 'Samsung Galaxy'), ('Google Pixel', 'Google pixel'), ('Xromi', 'Xromi')], max_length=100)),
                ('url', models.URLField()),
                ('video', models.URLField(verbose_name='Видео')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
