# Generated by Django 5.1.1 on 2024-09-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='url',
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_make',
            field=models.CharField(choices=[('IPhone', 'IPhone'), ('Samsung Galaxy', 'Samsung Galaxy'), ('Google Pixel', 'Google pixel'), ('Xromi', 'Xromi')], max_length=100, verbose_name='Модель'),
        ),
    ]
