# Generated by Django 5.1.1 on 2024-09-24 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_remove_phone_url_alter_phone_phone_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_make',
            field=models.CharField(choices=[('IPhone', 'IPhone'), ('Samsung Galaxy', 'Samsung Galaxy'), ('Google Pixel', 'Google pixel'), ('Xiaomi ', 'Xiaomi ')], max_length=100, verbose_name='Модель'),
        ),
        migrations.CreateModel(
            name='CommentPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField()),
                ('rate_starts', models.CharField(choices=[('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('phone_choice_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='phone.phone')),
            ],
        ),
    ]
