# Generated by Django 5.1.1 on 2024-09-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_post_url_alter_post_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='created_date',
        ),
    ]
